# Generated by Django 2.2 on 2019-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(db_index=True, max_length=100)),
                ('telefon', models.CharField(db_index=True, max_length=100)),
                ('bursa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localitate', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'studenti',
                'ordering': ('nume',),
            },
        ),
    ]
