# Generated by Django 2.2 on 2019-05-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'ordering': ('nume',), 'verbose_name': 'produs', 'verbose_name_plural': 'produse'},
        ),
    ]
